name: pipeline-master

on:
  push:
    branches: [ master, develop ]

env:
  MAVEN_PUBLISHING_USER: ${{ github.actor }}
  MAVEN_PUBLISHING_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}
  MAVEN_PUBLISHING_URL: https://maven.pkg.github.com/soffa-io/artifacts
  PRV_MAVEN_URL: https://maven.pkg.github.com/soffa-io/artifacts
  PRV_MAVEN_USER: ${{ github.actor }}
  PRV_MAVEN_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}
  SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
  SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
  SONATYPE_GPG: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run checks
        run: gradle check

  publish-to-github:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Publish snapshot artifact to Github
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: gradle publish -x test -Psnapshot=true
      - name: Publish artifact to Github
        if: ${{ github.ref == 'refs/heads/master' }}
        run: gradle publish -x test -Prelease=true

  publish-to-sonatype:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Publish artifact to public Sonatype Nexus
        run: |
          echo $SONATYPE_GPG | base64 -d > $HOME/.sonatype-keys.gpg
          gradle sign -x check publishMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository \
            -Psonatype=true \
            -PossrhUsername=$SONATYPE_USERNAME \
            -PossrhPassword=$SONATYPE_PASSWORD \
            -Psigning.keyId=$SIGNING_KEYID  \
            -Psigning.password=$SIGNING_PASSWORD \
            -Psigning.secretKeyRingFile=$HOME/.sonatype-keys.gpg

